# Generated by Django 4.2.4 on 2023-10-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('pregunta1', models.TextField()),
                ('pregunta2', models.TextField()),
                ('pregunta3', models.TextField()),
                ('pregunta4', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('datafono', 'Datafono'), ('todas', 'Todas')], max_length=20)),
                ('pregunta5', models.TextField()),
                ('pregunta6', models.TextField()),
                ('pregunta7', models.CharField(choices=[('de 1 a 5 años', 'De 1 a 5 años'), ('de 6 a 10 años', 'De 6 a 10 años'), ('de 11 a 15 años', 'De 11 a 15 años'), ('más de 15 años', 'Más de 15 años')], max_length=20)),
                ('pregunta8', models.TextField()),
                ('pregunta9', models.TextField()),
                ('pregunta10', models.TextField()),
                ('pregunta11', models.CharField(choices=[('una persona', 'Una persona'), ('dos personas', 'Dos personas'), ('tres personas', 'Tres personas'), ('mas de tres personas', 'Mas de tres personas')], max_length=20)),
                ('pregunta12', models.TextField()),
            ],
        ),
    ]
