# Generated by Django 4.2.4 on 2023-10-30 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuestaencuesta',
            old_name='apellidos',
            new_name='cargo',
        ),
        migrations.RemoveField(
            model_name='respuestaencuesta',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='respuestaencuesta',
            name='fecha',
        ),
    ]
